In [24]:
!pip install opencv-python

In [25]:
!pip install opencv_contrib_python

In [26]:
!pip install --upgrade pip setuptools wheel

imread() 開啟圖片

In [4]:
import cv2
img = cv2.imread('meme.jpg')   # 開啟圖片，預設使用 cv2.IMREAD_COLOR 模式
cv2.imshow('oxxostudio', img)  # 使用名為 oxxostudio 的視窗開啟圖片
cv2.waitKey(0)                 # 按下任意鍵停止
cv2.destroyAllWindows()        # 結束所有圖片視窗

In [1]:
import cv2
img = cv2.imread('meme.jpg', cv2.IMREAD_GRAYSCALE)   # 以灰階模式開啟圖片
cv2.imwrite('oxxostudio_2.jpg', img, [cv2.IMWRITE_JPEG_QUALITY, 80])  # 存成 jpg
cv2.imwrite('oxxostudio_3.png', img)  # 存成 png

True

OpenCV 裡的顏色為「BGR」

In [3]:
import cv2
import numpy as np
img = np.zeros((500,500,3), dtype='uint8')   # 快速產生 500x500，每個項目為 [0,0,0] 的三維陣列
img[150:350, 150:350] = [0,0,255]  # 將中間 200x200 的每個項目內容，改為 [0,0,255]
cv2.imwrite('oxxostudio.jpg', img)       # 存成 jpg
cv2.imshow('oxxostudio', img)            # 顯示圖片
cv2.waitKey(0)                           # 按下任意鍵停止
cv2.destroyAllWindows()

用VideoCapture() 開啟影片

In [10]:
cap = cv2.VideoCapture(0, cv2.CAP_DSHOW)

In [14]:
import cv2
cap = cv2.VideoCapture(0)
if not cap.isOpened():
    print("Cannot open camera")
    exit()

In [12]:
import cv2
cap = cv2.VideoCapture(0)
if not cap.isOpened():
    print("Cannot open camera")
    exit()
while True:
    ret, frame = cap.read()             # 讀取影片的每一幀
    if not ret:
        print("Cannot receive frame")   # 如果讀取錯誤，印出訊息
        break
    cv2.imshow('oxxostudio', frame)     # 如果讀取成功，顯示該幀的畫面
    if cv2.waitKey(1) == ord('q'):      # 每一毫秒更新一次，直到按下 q 結束
        break
cap.release()                           # 所有作業都完成後，釋放資源
cv2.destroyAllWindows()                 # 結束所有視窗

搭配 cvtColor() 改變影片色彩

In [15]:
import cv2
cap = cv2.VideoCapture(0)
if not cap.isOpened():
    print("Cannot open camera")
    exit()
while True:
    ret, frame = cap.read()
    if not ret:
        print("Cannot receive frame")
        break
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)  # 轉換成灰階
    # gray = cv2.cvtColor(frame, 6)  # 也可以用數字對照 6 表示轉換成灰階
    cv2.imshow('oxxostudio', gray)
    if cv2.waitKey(1) == ord('q'):
        break
cap.release()
cv2.destroyAllWindows()

讀取串流圖片 MJPEG ( Motion JPEG )

In [5]:
import cv2
cap = cv2.VideoCapture('https://cctvn.freeway.gov.tw/abs2mjpg/bmjpg?camera=15771')

if not cap.isOpened():
    print("Cannot open camera")
    exit()
while True:
    ret, frame = cap.read()             # 讀取影片的每一幀
    if not ret:
        print("Cannot receive frame")   # 如果讀取錯誤，印出訊息
        # 出現錯誤就再讀取一次，避免程式到此處就停止
        cap = cv2.VideoCapture('https://cctvn.freeway.gov.tw/abs2mjpg/bmjpg?camera=15771')
        continue
    cv2.imshow('oxxostudio', frame)     # 如果讀取成功，顯示該幀的畫面
    if cv2.waitKey(1) == ord('q'):      # 每一毫秒更新一次，直到按下 q 結束
        break
cap.release()                           # 所有作業都完成後，釋放資源
cv2.destroyAllWindows()                 # 結束所有視窗

Cannot receive frame


使用 VideoWriter() 儲存影片

In [9]:
import cv2
cap = cv2.VideoCapture(0)                         # 讀取電腦攝影機鏡頭影像。
width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))    # 取得影像寬度
height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))  # 取得影像高度
fourcc = cv2.VideoWriter_fourcc(*'mp4v')          # 設定影片的格式為 MJPG
out = cv2.VideoWriter('output.mp4', fourcc, 20.0, (width,  height))  # 產生空的影片
if not cap.isOpened():
    print("Cannot open camera")
    exit()
while True:
    ret, frame = cap.read()
    if not ret:
        print("Cannot receive frame")
        break
    out.write(frame)       # 將取得的每一幀圖像寫入空的影片
    cv2.imshow('oxxostudio', frame)
    if cv2.waitKey(1) == ord('q'):
        break             # 按下 q 鍵停止
cap.release()
out.release()      # 釋放資源
cv2.destroyAllWindows()

搭配 cvtColor() 儲存為黑白的影片

In [8]:
import cv2
cap = cv2.VideoCapture(0)
width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
fourcc = cv2.VideoWriter_fourcc(*'mp4v')
out = cv2.VideoWriter('output.mov', fourcc, 20.0, (width,  height))
# 如果轉換成黑白影片後如果無法開啟，請加上 isColor=False 參數設定
# out = cv2.VideoWriter('output.mov', fourcc, 20.0, (width,  height), isColor=False)
if not cap.isOpened():
    print("Cannot open camera")
    exit()
while True:
    ret, frame = cap.read()
    if not ret:
        print("Cannot receive frame")
        break
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)  # 轉換成灰階
    out.write(gray)
    cv2.imshow('oxxostudio', gray)
    if cv2.waitKey(1) == ord('q'):
        break
cap.release()
out.release()
cv2.destroyAllWindows()

Cannot receive frame


In [9]:
# shape 取得長寬與色版數量
import cv2
img = cv2.imread('meme.jpg')
print(img.shape)            # 得到 (360, 480, 3)
cv2.imshow('oxxostudio', img)
cv2.waitKey(0)              # 按下任意鍵停止
cv2.destroyAllWindows()

(640, 640, 3)


In [10]:
# size 取得像素總數
# 像素總數為「寬 x 長 x 色版數量」
import cv2
img = cv2.imread('meme.jpg')
print(img.size)            # 518400 ( 360x480x3 )
cv2.imshow('oxxostudio', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

1228800


In [13]:
# dtype 取得數據類型
import cv2
img = cv2.imread('meme.jpg')
print(img.dtype)            # uint8
cv2.imshow('oxxostudio', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

uint8


In [16]:
# 使用 imread() 方法讀取的影像後，可以印出圖片的「三維陣列」資訊
import cv2
img = cv2.imread('meme.jpg')
print(img)
cv2.imshow('oxxostudio', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[[ 97 152  49]
  [ 97 152  49]
  [ 97 152  49]
  ...
  [ 97 152  49]
  [ 97 152  49]
  [ 97 152  49]]

 [[ 97 152  49]
  [ 97 152  49]
  [ 97 152  49]
  ...
  [ 97 152  49]
  [ 97 152  49]
  [ 97 152  49]]

 [[ 97 152  49]
  [ 97 152  49]
  [ 97 152  49]
  ...
  [ 97 152  49]
  [ 97 152  49]
  [ 97 152  49]]

 ...

 [[ 97 152  49]
  [ 97 152  49]
  [ 97 152  49]
  ...
  [ 97 152  49]
  [ 97 152  49]
  [ 97 152  49]]

 [[ 97 152  49]
  [ 97 152  49]
  [ 97 152  49]
  ...
  [ 97 152  49]
  [ 97 152  49]
  [ 97 152  49]]

 [[ 97 152  49]
  [ 97 152  49]
  [ 97 152  49]
  ...
  [ 97 152  49]
  [ 97 152  49]
  [ 97 152  49]]]


In [17]:
import cv2
img = cv2.imread('meme.jpg')
b, g, r = cv2.split(img)
print(b)
print(g)
print(r)
cv2.imshow('oxxostudio', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[97 97 97 ... 97 97 97]
 [97 97 97 ... 97 97 97]
 [97 97 97 ... 97 97 97]
 ...
 [97 97 97 ... 97 97 97]
 [97 97 97 ... 97 97 97]
 [97 97 97 ... 97 97 97]]
[[152 152 152 ... 152 152 152]
 [152 152 152 ... 152 152 152]
 [152 152 152 ... 152 152 152]
 ...
 [152 152 152 ... 152 152 152]
 [152 152 152 ... 152 152 152]
 [152 152 152 ... 152 152 152]]
[[49 49 49 ... 49 49 49]
 [49 49 49 ... 49 49 49]
 [49 49 49 ... 49 49 49]
 ...
 [49 49 49 ... 49 49 49]
 [49 49 49 ... 49 49 49]
 [49 49 49 ... 49 49 49]]


In [19]:
# 透過陣列切片賦值的方法，就能將一張去除圖片中的紅色、綠色或藍色。
import cv2
img_blue = cv2.imread('meme.jpg')
img_green = cv2.imread('meme.jpg')
img_red = cv2.imread('meme.jpg')
img_blue[:,:,1] = 0    # 將綠色設為 0
img_blue[:,:,2] = 0    # 將紅色設為 0
img_green[:,:,0] = 0   # 將藍色設為 0
img_green[:,:,2] = 0   # 將紅色設為 0
img_red[:,:,0] = 0     # 將藍色設為 0
img_red[:,:,1] = 0     # 將綠色設為 0
cv2.imshow('oxxostudio blue', img_blue)
cv2.imshow('oxxostudio green', img_green)
cv2.imshow('oxxostudio red', img_red)
cv2.waitKey(0)
cv2.destroyAllWindows()

使用 flip() 方法，可以將影像上下左右翻轉。flip 有一個參數，參數設定如下：
0	以 x 軸為中心上下翻轉。
1	以 y 軸為中心左右翻轉。
-1	同時進行上下左右翻轉。

In [2]:
import cv2
img = cv2.imread('meme.jpg')   # 開啟圖片
output_0 = cv2.flip(img, 0)    # 上下翻轉
output_1 = cv2.flip(img, 1)    # 左右翻轉
output_2 = cv2.flip(img, -1)   # 上下左右翻轉
cv2.imwrite('meme_0.jpg', output_0)
cv2.imwrite('meme_1.jpg', output_1)
cv2.imwrite('meme_2.jpg', output_2)

True

使用 transpose()，將影像「左右翻轉後逆時針」旋轉 90 度

In [3]:
import cv2
img = cv2.imread('meme.jpg')
output = cv2.transpose(img)    # 逆時針旋轉 90 度。
cv2.imwrite('output.jpg', output)

True

使用 reize()，將影像輸出為指定的尺寸

In [4]:
import cv2
img = cv2.imread('meme.jpg')
output_1 = cv2.resize(img, (200, 200))   # 產生 200x200 的圖
output_2 = cv2.resize(img, (100, 300))   # 產生 100x300 的圖
cv2.imwrite('output_1.jpg', output_1)
cv2.imwrite('output_2.jpg', output_2)

True

將讀取到的影像縮小為 640x360，並進行上下翻轉

In [7]:
import cv2
cap = cv2.VideoCapture(0)                         # 讀取電腦攝影機鏡頭影像。
fourcc = cv2.VideoWriter_fourcc(*'mp4v')          # 設定影片的格式
out = cv2.VideoWriter('output_1.mp4', fourcc, 20.0, (640,  360))  # 產生空的影片，尺寸為 640x360
if not cap.isOpened():
    print("Cannot open camera")
    exit()
while True:
    ret, frame = cap.read()
    if not ret:
        print("Cannot receive frame")
        break
    img_1 = cv2.resize(frame,(640, 360))   # 改變圖片尺寸
    img_2 = cv2.flip(img_1, 0)             # 上下翻轉
    out.write(img_2)                       # 將取得的每一幀圖像寫入空的影片
    cv2.imshow('oxxostudio', frame)
    if cv2.waitKey(1) == ord('q'):
        break                              # 按下 q 鍵停止
cap.release()
out.release()      # 釋放資源
cv2.destroyAllWindows()

warpAffine() 方法可以將來源的圖像，根據指定的「仿射矩陣」，輸出成仿射轉換後的新影像，矩陣必須採用 numpy 的矩陣格式，使用的方法如下：

cv2.warpAffine(img, M, (w, h))
#img 來源圖像，M 仿射矩陣，(w, h) 圖片長寬

In [2]:
import cv2
import numpy as np
img = cv2.imread('meme.jpg')
M = np.float32([[1, 0, 100], [0, 1, 100]]) # 2x3 矩陣，x 軸平移 100，y 軸平移 100
output_3 = cv2.warpAffine(img, M, (480, 360))
cv2.imwrite('output_3.jpg', output_3)

True

getRotationMatrix2D() 方法可以產生旋轉指定角度影像的仿射矩陣，再透過 warpAffine() 產生旋轉的影像，使用方式如下：

cv2.getRotationMatrix2D((x, y), angle, scale)
#(x, y) 旋轉的中心點，angle 旋轉角度 ( - 順時針，+ 逆時針 )，scale 旋轉後的尺寸

In [1]:
import cv2
img = cv2.imread('meme.jpg')
M = cv2.getRotationMatrix2D((240, 180), 45, 1)    # 中心點 (240, 180)，旋轉 45 度，尺寸 1
output_4 = cv2.warpAffine(img, M, (480, 360))
cv2.imwrite('output_4.jpg', output_4)

True

getAffineTransform() 方法，可以根據輸入影像的三個點，對應輸出影像的三個點，產生仿射矩陣，再透過 warpAffine() 產生仿射變換後的影像，使用 2x3 的 numpy 矩陣作為三個點的座標格式，使用方法如下：

cv2.getAffineTransform(輸入影像三個點的座標，輸出影像三個點的座標)

In [6]:
import cv2
import numpy as np
img = cv2.imread('meme.jpg')
p1 = np.float32([[100,100],[480,0],[0,360]])
p2 = np.float32([[0,0],[480,0],[0,360]])
M = cv2.getAffineTransform(p1, p2)
output_5 = cv2.warpAffine(img, M, (480, 360))
cv2.imwrite('output_5.jpg', output_5)

True

warpPerspective() 方法為影像透視的方法，根據指定的「透視矩陣」，輸出成透視轉換後的新影像，使用方法如下：

cv2.warpPerspective(img, M, (w, h))
#img 來源圖像，M 透視矩陣，(w, h) 圖片長寬

getPerspectiveTransform() 方法，可以根據輸入影像的四個點，對應輸出影像的四個點，產生透視矩陣，再透過 warpPerspective() 產生透視變換後的影像，使用 2x4 的 numpy 矩陣作為四個點的座標格式，使用方法如下：

cv2.getPerspectiveTransform(輸入影像四個點的座標，輸出影像四個點的座標)

In [7]:
import cv2
import numpy as np

p1 = np.float32([[100,100],[480,0],[0,360],[480,360]])
p2 = np.float32([[0,0],[480,0],[0,360],[480,360]])
m = cv2.getPerspectiveTransform(p1,p2)

img = cv2.imread('meme.jpg')
output_6 = cv2.warpPerspective(img, m, (480, 360))
cv2.imwrite('output_6.jpg', output_6)

True

使用 cvtcolor()，將轉換影像色彩，把來源的彩色圖片，轉換成灰階影像

In [9]:
import cv2
img = cv2.imread('meme.jpg')
img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)  # 轉換成灰階影像
cv2.imwrite('oxxo.jpg', img)
cv2.waitKey(0)                               # 按下任意鍵停止
cv2.destroyAllWindows()

將來源的彩色影片，轉換成灰階影片

In [10]:
import cv2
cap = cv2.VideoCapture(0)
if not cap.isOpened():
    print("Cannot open camera")
    exit()
while True:
    ret, frame = cap.read()
    if not ret:
        print("Cannot receive frame")
        break
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)  # 轉換成灰階影像
    cv2.imshow('oxxostudio', gray)
    if cv2.waitKey(1) == ord('q'):
        break      # 按下 q 鍵停止
cap.release()
cv2.destroyAllWindows()

line() 方法可以在影像裡繪製直線
cv2.line(img, pt1, pt2, color, thickness)
#img 來源影像
#pt1 起始點座標 pt2 結束點座標
#color 線條顏色，使用 BGR
#thickness 線條粗細，預設 1

In [1]:
import cv2
import numpy as np
img = np.zeros((300,300,3), dtype='uint8')   # 繪製 300x300 的黑色畫布
cv2.line(img,(50,50),(250,250),(0,0,255),5)  # 繪製線條
cv2.imshow('oxxostudio', img)
cv2.waitKey(0)                               # 按下任意鍵停止
cv2.destroyAllWindows()

arrowedLine() 方法可以在影像裡繪製箭頭線條，使用方法如下：

cv2.arrowedLine(img, pt1, pt2, color, thickness, tipLength)
#img 來源影像
#pt1 起始點座標 pt2 結束點座標
#color 線條顏色，使用 BGR
#thickness 線條粗細，預設 1
#tipLength 箭頭長度，預設 0.1 ( 箭頭線條長度 x 0.1 )

In [2]:
import cv2
import numpy as np
img = np.zeros((300,300,3), dtype='uint8')
cv2.arrowedLine(img,(50,50),(250,250),(0,0,255),5)  # 繪製箭頭線條
cv2.imshow('oxxostudio', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

rectangle() 方法可以在影像裡繪製四邊形，使用方法如下：

cv2.rectangle(img, pt1, pt2, color, thickness)
#img 來源影像
#pt1 左上座標 pt2 右下座標
#color 線條顏色，使用 BGR
#thickness 線條粗細，預設 1，設定 -1 表示填滿

In [4]:
import cv2
import numpy as np
img = np.zeros((300,300,3), dtype='uint8')
cv2.rectangle(img,(50,50),(250,250),(0,0,255),-1) # 繪製正方形
cv2.imshow('oxxostudio', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

circle() 方法可以在影像裡繪製圓形，使用方法如下：

cv2.circle(img, center, radius, color, thickness)
#img 來源影像
#center 中心點座標
#radius 半徑
#color 線條顏色，使用 BGR
#thickness 線條粗細，預設 1，設定 -1 表示填滿

In [6]:
import cv2
import numpy as np
img = np.zeros((300,300,3), dtype='uint8')
cv2.circle(img,(150,150),100,(0,0,255),-1) # 繪製圓形
cv2.imshow('oxxostudio', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

ellipse() 方法可以在影像裡繪製橢圓形，使用方法如下：

cv2.ellipse(img, center, axes, angle, startAngle, endAngle, color, thickness)
#img 來源影像
#center 中心點座標
#axes 長軸與短軸
#angle 轉向角度，正值逆時針，負值順時針
#startAngle 起始角度，endAngle 結束角度，範圍 0～360
#color 線條顏色，使用 BGR
#thickness 線條粗細，預設 1，設定 -1 表示填滿

In [9]:
import cv2
import numpy as np
img = np.zeros((300,300,3), dtype='uint8')
cv2.ellipse(img,(150,150),(100,50),45,0,360,(0,0,255),5)
cv2.ellipse(img,(150,150),(30,100),90,0,360,(255,150,0),5)
cv2.ellipse(img,(150,150),(20,120),30,0,360,(0,255,255),5)
cv2.imshow('oxxostudio', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

polylines() 方法可以在影像裡繪製多邊形，使用方法如下：

cv2.polylines(img, pts, isClosed, color, thickness)
#img 來源影像
#pts 座標陣列 ( 使用 numpy 陣列 )
#isClosed 多邊形是否閉合，True 閉合，False 不閉合
#color 線條顏色，使用 BGR
#thickness 線條粗細，預設 1

In [10]:
import cv2
import numpy as np
img = np.zeros((300,300,3), dtype='uint8')
pts = np.array([[150,50],[250,100],[150,250],[50,100]])   # 產生座標陣列
cv2.polylines(img,[pts],True,(0,0,255),5)   # 繪製多邊形
cv2.imshow('oxxostudio', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

putText() 方法可以在影像裡加入文字，使用方法如下：

cv2.putText(img, text, org, fontFace, fontScale, color, thickness, lineType)
#img 來源影像
#text 文字內容
#org 文字座標 ( 垂直方向是文字底部到影像頂端的距離 )
#fontFace 文字字型
#fontScale 文字尺寸
#color 線條顏色，使用 BGR
#thickness 文字外框線條粗細，預設 1
#lineType 外框線條樣式，預設 cv2.LINE_8，設定 cv2.LINE_AA 可以反鋸齒

In [11]:
import cv2
import numpy as np
img = np.zeros((150,300,3), dtype='uint8')   # 建立 300x150 的黑色畫布
text = 'Hello'
org = (20,90)
fontFace = cv2.FONT_HERSHEY_SIMPLEX
fontScale = 2.5
color = (0,0,255)
thickness = 5
lineType = cv2.LINE_AA
cv2.putText(img, text, org, fontFace, fontScale, color, thickness, lineType)
cv2.imshow('oxxostudio', img)
cv2.waitKey(0)      # 按下任意鍵停止
cv2.destroyAllWindows()

在讀取影像後，使用陣列的切片方式，取出想要的範圍，另存成新的圖片，就可以實現剪裁圖片的效果，下方的程式碼會從圖片中 (100,100) 的位置，剪裁出一個 200x200 的區域儲存為新影像。

In [14]:
import cv2
img = cv2.imread('meme.jpg')
x = 100
y = 100
w = 200
h = 200
crop_img = img[y:y+h, x:x+w]        # 取出陣列的範圍
cv2.imwrite('output.jpg', crop_img) # 儲存圖片
cv2.imshow('oxxostudio', crop_img)
cv2.waitKey(0)                      # 按下任意鍵停止
cv2.destroyAllWindows()

運用同樣的原理 ( 剪裁出來的區域是陣列 )，就能將剪裁的區域，放到其他圖片中指定的位置，下方的程式碼，會將剪裁出來的圖片，放到另外一張黑色畫布中 (100, 100) 的位置。

In [16]:
import cv2
import numpy as np
img = cv2.imread('meme.jpg')
x = 100
y = 100
w = 200
h = 200
crop_img = img[y:y+h, x:x+w]

output = np.zeros((360,480,3), dtype='uint8')
output[x:x+w, y:y+h]=crop_img

cv2.imwrite('output.jpg', output)
cv2.imshow('oxxostudio', output)
cv2.waitKey(0)
cv2.destroyAllWindows()

調整 contrast ( 對比 ) 和 brightness ( 亮度 ) 的數值，去改變影像的對比度和亮度。

In [18]:
import cv2
import numpy as np
img = cv2.imread('mona.jpg')

contrast = 200
brightness = 0
output = img * (contrast/127 + 1) - contrast + brightness # 轉換公式
# 轉換公式參考 https://stackoverflow.com/questions/50474302/how-do-i-adjust-brightness-contrast-and-vibrance-with-opencv-python

# 調整後的數值大多為浮點數，且可能會小於 0 或大於 255
# 為了保持像素色彩區間為 0～255 的整數，所以再使用 np.clip() 和 np.uint8() 進行轉換
output = np.clip(output, 0, 255)
output = np.uint8(output)

cv2.imshow('before', img)    # 原始圖片
cv2.imshow('after', output) # 調整亮度對比的圖片
cv2.waitKey(0)                    # 按下任意鍵停止
cv2.destroyAllWindows()

使用 convertScaleAbs 方法，可以根據特定的公式，轉換影像中每個像素，使用方法如下：

cv2.convertScaleAbs(img, output, alpha, beta)
#img 來源影像
#output 輸出影像，公式：output = img*alpha + beta
#alpha, beta 公式中的參數

In [27]:
import cv2
import numpy as np
img = cv2.imread('mona.jpg')
output = img    # 建立 output 變數

alpha = 1
beta = 10

cv2.convertScaleAbs(img, output, alpha, beta)  # 套用 convertScaleAbs
cv2.imshow('oxxostudio', output)
cv2.waitKey(0)      # 按下任意鍵停止
cv2.destroyAllWindows()